### ISSUE TITLE
DEAP no longer installs on Python 3.10

### ISSUE THREAD

**Issue by bje-** [DEAP/deap#658] opened 2022-08-02 07:58 UTC
In Python 3.10, `lib2to3` was removed and so was the `use_2to3` option in `setuptools`. The fix is to port the whole codebase to Python 3 and remove `use_2to3` from `setup.py`. For more information, see: https://github.com/pypa/setuptools/issues/2086

This is a major problem.

**Comment by Edanflame** [comment] 2022-08-03 08:54
this maybe a large  work and if you only want to installs the latest deap in python 3.10, you can refer #610

**Comment by bje-** [comment] 2022-08-03 08:56
I can't see why it should be a lot of hard work. Currently, DEAP relies on `lib2to3` to do the translation and everything works fine. I would suggest that one run of `2to3 --write` over the whole source tree would do the job.

**Comment by fmder** [comment] 2022-08-03 10:37
@bje- The problem is that the source it produces is very ugly. Plus there is a new branch that would use a lot of new Python features almost ready but the documentation, which I think is the string point of deap, would be mostly obsolete and need a major rework.

**Comment by fmder** [comment] 2022-08-03 10:39
But you are right, this is long overdue...

**Comment by bje-** [comment] 2022-08-03 10:55
> @bje- The problem is that the source it produces is very ugly.

Really? I ran `2to3` and it makes fairly minimal changes to make the code Python 3 compliant. See https://github.com/DEAP/deap/pull/659

**Comment by bje-** [comment] 2022-08-04 21:27
I have [a fork](https://github.com/bje-/deap) that has been processed by `2to3`. It is working fine and my package is having to use this fork for the time being so that DEAP can run on Python 3.10.

**Comment by fmder** [comment] 2022-08-07 17:02
Fixed by #625

**Closed by fmder** 2022-08-07 17:02 UTC
